### 注册用户
POST http://localhost:8004/admin/passport/signup
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "name": "14131913",
  "password": "123456",
  "captcha_id": "XgxjDNvGFIuBjUYfWggb",
  "captcha_code": "676832"
}

### 用户登录
POST http://localhost:8004/admin/passport/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "name": "14131913",
  "password": "123456",
  "captcha_id": "2uVP5dd1mOIw0ShdNNc7",
  "captcha_code": "472991"
}

### 用户注销
POST http://localhost:8004/admin/passport/logout
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

### 获取个人账户信息
POST http://localhost:8004/admin/passport/info
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

### 修改个人账户信息
POST http://localhost:8004/admin/passport/modify
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "displayName": "显示1名",
  "password": "123456",
  "newpass": "456789",
  "email": "459685578@qq.com",
  "company": "安徽旭帆",
  "phone": "1825543957"
}

###

