### 获取视频回看
POST http://localhost:8004/admin/record/info
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Cookie: rtcadmin=test

{
  "id": 1
}

### 获取视频回看列表
POST http://localhost:8004/admin/record/list
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Cookie: rtcadmin=test

{
  "page": 0,
  "perPage": 10
}

### 删除视频回看
POST http://localhost:8004/admin/record/delete
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Cookie: rtcadmin=test

{
  "id": 1
}

###